# Generated by Django 5.0.6 on 2024-08-26 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('status', models.IntegerField()),
                ('due_date', models.DateTimeField(default=datetime.datetime(2024, 8, 26, 15, 41, 30, 692458))),
            ],
        ),
    ]
